version: '3'

services:
  postgres:
    image: docker.io/postgres:latest
    environment:
      POSTGRES_USER: ${GO_DB_USER}
      POSTGRES_PASSWORD: ${GO_DB_PASSWORD}
      POSTGRES_DB: ${GO_DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/postgress:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8081:80
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
